version: '3.8'
services:
  fast_api:
    build: ./fast_api
    ports:
      - "8000:8000"
    volumes:
      - ./fast_api:/fast_api
    networks:
      - app-network

  tg_bot:
    build: ./tg_bot
    depends_on:
      - fast_api
    volumes:
      - ./tg_bot:/tg_bot
    networks:
      - app-network

networks:
  app-network:
    driver: bridge