"""Database creation

Revision ID: 91f538006e0b
Revises: 
Create Date: 2024-06-29 19:09:11.432798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '91f538006e0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('telegram_id', sa.Integer(), nullable=False),
                    sa.Column('date_of_birth', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('telegram_id')
                    )
    op.create_table('subscriptions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('subscriber_id', sa.Integer(), nullable=False),
                    sa.Column('subscribed_to_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['subscribed_to_id'], ['users.telegram_id'], ),
                    sa.ForeignKeyConstraint(['subscriber_id'], ['users.telegram_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('users')
    # ### end Alembic commands ###
